// Top 50 US health systems supporting Apple Health Records (Epic/Cerner FHIR)
export const SUPPORTED_HOSPITALS = [
  'Atrium Health',
  'Banner Health',
  'Baylor Scott & White Health',
  'Beth Israel Deaconess Medical Center',
  'BJC Healthcare',
  "Boston Children's Hospital",
  "Brigham and Women's Hospital",
  'CHRISTUS Health',
  'Cleveland Clinic',
  'CommonSpirit Health',
  'Dartmouth Health',
  'Duke Health',
  'Emory Healthcare',
  'Froedtert Health',
  'Geisinger',
  'HCA Healthcare',
  'Houston Methodist',
  'Indiana University Health',
  'Johns Hopkins Medicine',
  "Lurie Children's Hospital",
  'Mass General Brigham',
  'Mayo Clinic',
  'MedStar Health',
  'Memorial Hermann Health System',
  'Michigan Medicine',
  'Mount Sinai Health System',
  'NewYork-Presbyterian',
  'Northwell Health',
  'Northwestern Medicine',
  'NYU Langone Health',
  'OhioHealth',
  'OSF HealthCare',
  'Penn Medicine',
  'Providence Health & Services',
  'SCL Health',
  'Scripps Health',
  'SSM Health',
  'Stanford Health Care',
  "St. Jude Children's Research Hospital",
  'Sutter Health',
  'Texas Health Resources',
  'The Ohio State University Wexner Medical Center',
  'UCHealth',
  'UF Health',
  'UMass Memorial Health',
  'UNC Health',
  'University of Chicago Medicine',
  'UCSF Health',
  'Vanderbilt University Medical Center',
  'WakeMed',
]

export function searchHospitals(query: string): string[] {
  if (!query.trim()) return SUPPORTED_HOSPITALS
  const lower = query.toLowerCase()
  return SUPPORTED_HOSPITALS.filter((h) => h.toLowerCase().includes(lower))
}
